
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=kita
      - TZ=Asia/Tokyo
    volumes:
      - ./data/mysql:/var/lib/mysql:cached

  kita:
    container_name: kita
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./apps/kita:/var/www/html